version: "3.8"

services:
  reverse_proxy:
    image: nginx:stable
    ports:
      - "80:80"
    environment:
     - WEBAUTHN_RP_ID=
     - WEBAUTHN_RP_NAME=
     - WEBAUTHN_ORIGIN=

  app:
    image: passkeys-demo/app:latest